name: CI/CD for PMS Backend Image Build and Push

on:
  push:
    branches: [build-deploy-dockerimage]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build the Nest.js app
        run: npm run build

      - name: Get commit hash
        run: echo "COMMIT_HASH=$GITHUB_SHA" >> $GITHUB_ENV

      - name: Clone other repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2.2
        with:
          owner: "Remmy-coder"
          repository: "pmsbackend-k8s-iac"
          access-token: ${{ secrets.PAT_TOKEN }}

      - name: Update Image Tag in Deployment File
        run: |
         cd <repository-name>
         ls -la
