name: CI/CD for PMS Backend Image Build and Push

on:
  push:
    branches: [build-deploy-dockerimage]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build the Nest.js app
        run: npm run build

      - name: Build and Push Image to Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: remmyomeje/pms-repository
          registry: docker.io
          tags: latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
